# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc19e6b0d7df7a6b7865009d22224cb36336b97dc8658e024530346b7c963b9e438360f4fcf4f56516ac99296f732eae2c04382c8642415a2a7024a9c0850a4e

test:
  secret_key_base: 4417106cfe9e001ca2557ebd84405e6f9f4fc08287f84ad76ac527c75965f4b2691f9d19d6d39bb5b1bdc1f161049f7ba9f3f32abf272c105fc991330e8f8685

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
